// Email sequence data models
// Each Prospect gets exactly 3 emails: Day 1, Day 4, Day 7.
// All emails start as "draft" — human must approve before they are scheduled.

// ── Enums ──────────────────────────────────────────────────────────────────

export type EmailStatus =
  | "draft"      // generated by Writer agent, awaiting human review
  | "scheduled"  // approved by human, will send on scheduled_at
  | "sent"       // delivered to Resend successfully
  | "opened"     // prospect opened (Resend webhook)
  | "clicked"    // prospect clicked a link (Resend webhook)
  | "replied"    // prospect replied (Gmail polling)
  | "bounced"    // hard or soft bounce (Resend webhook)
  | "discarded"; // human chose not to send this email

export type SequenceDay = 1 | 4 | 7;

// ── Core Model ─────────────────────────────────────────────────────────────

export interface Email {
  id: string;              // UUID
  campaign_id: string;     // UUID
  prospect_id: string;     // UUID
  prospect_email: string;  // denormalised for quick display
  prospect_name: string;   // denormalised — "{first_name} {last_name}"

  sequence_day: SequenceDay; // which email in the 3-step sequence
  subject: string;
  body: string;              // plain text; newlines rendered as <br> in preview

  status: EmailStatus;
  resend_email_id: string | null; // returned by Resend after sending

  scheduled_at: string | null;  // ISO 8601 — 9 AM prospect local time
  sent_at: string | null;       // ISO 8601
  opened_at: string | null;     // ISO 8601
  replied_at: string | null;    // ISO 8601

  created_at: string;           // ISO 8601
}

// ── Update Request ─────────────────────────────────────────────────────────

export interface UpdateEmailRequest {
  subject?: string;
  body?: string;
}

// ── Grouped View (used on Campaign Detail screen) ─────────────────────────

export interface ProspectEmailGroup {
  prospect: import("./prospect").Prospect;
  emails: Email[]; // always sorted: Day 1 → Day 4 → Day 7
}

export interface CampaignEmailsResponse {
  campaign_id: string;
  grouped_by_prospect: ProspectEmailGroup[];
}

// ── UI Helpers ─────────────────────────────────────────────────────────────

/** True if the email can still be edited (not yet sent) */
export const isEditable = (status: EmailStatus): boolean =>
  status === "draft" || status === "scheduled";

/** True if the email can be approved (only drafts can be approved) */
export const isApprovable = (status: EmailStatus): boolean =>
  status === "draft";

/** True if the email has been actioned (no further action needed) */
export const isTerminal = (status: EmailStatus): boolean =>
  ["sent", "opened", "clicked", "replied", "bounced", "discarded"].includes(status);

/** Maps status to a badge label */
export const EMAIL_STATUS_LABEL: Record<EmailStatus, string> = {
  draft:     "Draft",
  scheduled: "Scheduled",
  sent:      "Sent",
  opened:    "Opened",
  clicked:   "Clicked",
  replied:   "Replied",
  bounced:   "Bounced",
  discarded: "Discarded",
};

/** Maps status to Tailwind colour classes */
export const EMAIL_STATUS_COLOR: Record<EmailStatus, string> = {
  draft:     "bg-gray-100 text-gray-600",
  scheduled: "bg-blue-100 text-blue-700",
  sent:      "bg-indigo-100 text-indigo-700",
  opened:    "bg-yellow-100 text-yellow-700",
  clicked:   "bg-orange-100 text-orange-700",
  replied:   "bg-green-100 text-green-700",
  bounced:   "bg-red-100 text-red-700",
  discarded: "bg-gray-100 text-gray-400 line-through",
};

/** Label for each sequence day */
export const SEQUENCE_DAY_LABEL: Record<SequenceDay, string> = {
  1: "Day 1 — First Touch",
  4: "Day 4 — Follow-up",
  7: "Day 7 — Break-up",
};

/**
 * Returns the next actionable status for a given email.
 * Used to determine which action button to show.
 */
export const getNextAction = (
  status: EmailStatus
): { label: string; action: "approve" | "send" | "discard" } | null => {
  if (status === "draft")      return { label: "Approve",  action: "approve" };
  if (status === "scheduled")  return { label: "Send Now", action: "send" };
  return null;
};
